ctrl_model_pinocchio_vs_franka:
  type: panda_torque_mpc/CtrlModelPinocchioVsFranka
  arm_id: $(arg arm_id)
  urdf_path: $(find panda_torque_mpc)/res/panda_inertias.urdf


ctrl_log_update_dt:
  type: panda_torque_mpc/CtrlLogUpdateDt
  arm_id: $(arg arm_id)


ctrl_playback_pd_plus:
    type: panda_torque_mpc/CtrlPlaybackPDplus
    arm_id: $(arg arm_id)
    urdf_path: $(find panda_torque_mpc)/res/panda_inertias.urdf
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
    # traj_dir: "/home/mfourmy/Downloads/tsid_panda_traj_slow/"
    traj_dir: "/home/mfourmy/Downloads/croco_panda_traj_slow/"
    # traj_dir: "/home/mfourmy/Downloads/croco_panda_traj_mid/"
    # traj_dir: "/home/mfourmy/Downloads/croco_panda_traj_fast/"
    # traj_dir: "/home/mfourmy/Downloads/croco_panda_traj_fffast/"
    scale_ff: 1.0 
    Kp: 50 
    Kd: 5 
    publish_rate: 10.0
    alpha_dq_filter: 0.99 # should be close to 1 and <= 1.0
    saturate_dtau: true


ctrl_joint_space_ID:
    type: panda_torque_mpc/CtrlJointSpaceID
    arm_id: $(arg arm_id)
    urdf_path: $(find panda_torque_mpc)/res/panda_inertias.urdf
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
    # Gains for IDControl
    Kp: 500  # Stiff
    Kd: 50  # Stiff
    # Kp: 100 
    # Kd: 10 
    # Kp: 50
    # Kd: 5
    # Gains for IDControlSimplified
    kp_gains:
        - 60.0
        - 60.0
        - 60.0
        - 60.0
        - 20.0
        - 10.0
        - 5.0
    kd_gains:
        - 5.0
        - 5.0
        - 5.0
        - 2.0
        - 2.0
        - 2.0
        - 1.0
    # Trajectory simulation
    delta_q:
        - -0.3
        -  0.3
        -  0.3
        -  0.3
        -  0.3
        -  0.3
        -  0.3
    period_q:
        - 5.0
        - 5.0
        - 5.0
        - 5.0
        - 5.0
        - 5.0
        - 5.0
    publish_rate: 10.0
    # 0: IDControl
    # 1: IDControlSimplified
    # 2: PDGravity
    # 3: PureGravity
    control_variant: 3
    use_pinocchio: true
    alpha_dq_filter: 0.99 # should be close to 1 and <= 1.0
    saturate_dtau: true


ctrl_task_space_ID:
    type: panda_torque_mpc/CtrlTaskSpaceID
    arm_id: $(arg arm_id)
    urdf_path: $(find panda_torque_mpc)/res/panda_inertias.urdf
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
    # Trajectory simulation
    delta_nu:
        - 0.09
        - 0.09
        - 0.09
        - 0.0
        - 0.0
        - 0.0
    period_nu:
        - 4.0
        - 4.0
        - 4.0
        - 5.0
        - 5.0
        - 5.0
    publish_rate: 10.0
    use_external_pose_publisher: false
    # 0: PosiPosture
    # 1: PosePosture  # TODO: not working -> pbe in jacobian
    # 2: TSID
    control_variant: 2
    use_pinocchio: true
    alpha_dq_filter: 1.0 # should be close to 1 and <= 1.0
    # Controller configs
    kp_ee: 500  # Stiff
    kd_ee: 200 
    # kp_ee: 100 
    # kd_ee: 60 
    # kp_ee: 20
    # kd_ee: 5 
    kp_q: 100
    kd_q: 40
    w_ee: 1
    w_q: 0.001
    tau_limit_scale: 0.5
    v_limit_scale: 0.6
    ee_task_mask: [1,1,1,1,1,1]
    # ee_task_mask: [1,1,1,0,0,0]



ctrl_mpc_croco:
    type: panda_torque_mpc/CtrlMpcCroco
    arm_id: $(arg arm_id)
    urdf_path: $(find panda_torque_mpc)/res/panda_inertias.urdf
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
    # Trajectory simulation
    delta_nu:
        - 0.09
        - 0.09
        - 0.09
        - 0.0
        - 0.0
        - 0.0
    period_nu:
        - 4.0
        - 4.0
        - 4.0
        - 5.0
        - 5.0
        - 5.0
    publish_rate: 10.0
    # use_external_pose_publisher: true
    alpha_dq_filter: 1.0 # should be close to 1 and <= 1.0
    ####################
    # Controller configs
    nb_shooting_nodes: 10
    dt_ocp: 0.01
    nb_iterations_max: 1
    # armature: [0.1,0.1,0.1,0.1,0.1,0.1,0.1]
    armature: [0.0,0.0,0.0,0.0,0.0,0.0,0.0]
    
    w_frame_running:  100
    w_frame_terminal: 100
    w_x_reg_running: 0.1
    w_x_reg_terminal: 1.0
    scale_q_vs_v_reg: 0.1
    w_u_reg_running: 0.01
    diag_u_reg_running: [1.0,1.0,1.0,1.0,1.0,1.0,1.0]