ctrl_model_pinocchio_vs_franka:
  type: panda_torque_mpc/CtrlModelPinocchioVsFranka
  arm_id: $(arg arm_id)
  urdf_path: $(find panda_torque_mpc)/urdf/panda_inertias.urdf


ctrl_log_update_dt:
  type: panda_torque_mpc/CtrlLogUpdateDt
  arm_id: $(arg arm_id)


ctrl_playback_pd_plus:
    type: panda_torque_mpc/CtrlPlaybackPDplus
    arm_id: $(arg arm_id)
    urdf_path: $(find panda_torque_mpc)/urdf/panda_inertias.urdf
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
    # traj_dir: "/home/mfourmy/Downloads/tsid_panda_traj_slow/"
    traj_dir: "/home/mfourmy/Downloads/croco_panda_traj_slow/"
    # traj_dir: "/home/mfourmy/Downloads/croco_panda_traj_mid/"
    # traj_dir: "/home/mfourmy/Downloads/croco_panda_traj_fast/"
    # traj_dir: "/home/mfourmy/Downloads/croco_panda_traj_fffast/"
    scale_ff: 1.0 
    Kp: 50 
    Kd: 5 
    publish_rate: 10.0
    alpha_dq_filter: 0.99 # should be close to 1 and <= 1.0
    saturate_dtau: true


ctrl_joint_space_ID:
    type: panda_torque_mpc/CtrlJointSpaceID
    arm_id: $(arg arm_id)
    urdf_path: $(find panda_torque_mpc)/urdf/panda_inertias.urdf
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
    # Gains for IDControl
    Kp: 300  # Stiff
    Kd: 30  # Stiff
    # Kp: 100 
    # Kd: 10 
    # Kp: 50
    # Kd: 5
    # Gains for IDControlSimplified
    kp_gains:
        - 60.0
        - 60.0
        - 60.0
        - 60.0
        - 20.0
        - 10.0
        - 5.0
    kd_gains:
        - 5.0
        - 5.0
        - 5.0
        - 2.0
        - 2.0
        - 2.0
        - 1.0
    # Trajectory simulation
    delta_q:
        - -0.3
        -  0.3
        -  0.3
        -  0.3
        -  0.3
        -  0.3
        -  0.3
    period_q:
        - 5.0
        - 5.0
        - 5.0
        - 5.0
        - 5.0
        - 5.0
        - 5.0
    publish_rate: 10.0
    # 0: IDControl
    # 1: IDControlSimplified
    # 2: PDGravity
    # 3: PureGravity
    control_variant: 3
    use_pinocchio: true
    alpha_dq_filter: 0.99 # should be close to 1 and <= 1.0
    saturate_dtau: true


ctrl_task_space_ID:
    type: panda_torque_mpc/CtrlTaskSpaceID
    arm_id: $(arg arm_id)
    urdf_path: $(find panda_torque_mpc)/urdf/panda_inertias.urdf
    ee_frame_name: panda_hand
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
    # Trajectory simulation
    delta_nu:
        - 0.00
        - 0.00
        - 0.00
        - 0.0
        - 0.0
        - 0.0
    period_nu:
        - 4.0
        - 4.0
        - 4.0
        - 5.0
        - 5.0
        - 5.0
    publish_rate: 10.0
    use_external_pose_publisher: false
    # 0: PosiPosture
    # 1: PosePosture  # TODO: not working -> pbe in jacobian
    # 2: TSIDPose
    control_variant: 2
    use_pinocchio: true
    alpha_dq_filter: 1.0 # should be close to 1 and <= 1.0
    # Controller configs
    # kp_ee: 500  # Stiff
    # kd_ee: 200 
    kp_ee: 100 
    kd_ee: 60 
    # kp_ee: 20
    # kd_ee: 5 
    kp_q: 100
    kd_q: 40
    w_ee: 1
    w_q: 0.001
    tau_limit_scale: 0.8
    v_limit_scale: 0.8
    # ee_task_mask: [1,1,1,1,1,1]
    ee_task_mask: [1,1,1,0,0,0]


# TOFIX!
# TOFIX!
# TOFIX!
# TOFIX!
ctrl_mpc_croco:
    type: panda_torque_mpc/CtrlMpcCroco
    arm_id: $(arg arm_id)
    urdf_path: $(find panda_torque_mpc)/urdf/panda_inertias.urdf
    ee_frame_name: panda_hand
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7
    # Trajectory simulation
    delta_nu:
        - 0.07
        - 0.08
        - 0.09
        - 0.0
        - 0.0
        - 0.0
    period_nu:
        - 5.0
        - 5.0
        - 5.0
        - 5.0
        - 5.0
        - 5.0
    publish_rate: 10.0
    use_external_pose_publisher: true
    alpha_dq_filter: 1.0 # should be close to 1 and <= 1.0
    ####################
    # Controller configs
    nb_shooting_nodes: 10
    dt_ocp: 0.01
    nb_iterations_max: 1
    reference_is_placement: false   # otherwise, translation
    armature: [0.1,0.1,0.1,0.1,0.1,0.1,0.1]
    # armature: [0.0,0.0,0.0,0.0,0.0,0.0,0.0]
    
    # w_frame_running:  100
    # w_frame_terminal: 100
    w_frame_running:  20
    w_frame_terminal: 20
    w_x_reg_running: 0.1
    w_x_reg_terminal: 1.0
    scale_q_vs_v_reg: 0.1
    w_u_reg_running: 0.01
    diag_u_reg_running: [1.0,1.0,1.0,1.0,1.0,1.0,1.0]



ctrl_mpc_linearized:
    type: panda_torque_mpc/CtrlMpcLinearized
    arm_id: $(arg arm_id)
    urdf_path: $(find panda_torque_mpc)/urdf/panda_inertias.urdf
    ee_frame_name: panda_hand
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7

    publish_rate: 10.0
    alpha_dq_filter: 1.0 # should be close to 1 and <= 1.0

    ###############
    # JSID init controller params 
    Kp_jsid: 80 
    Kd_jsid: 10 
    dt_transition_jsid_to_mpc: 0.5

    ####################
    # OCP motion server configs
    nb_shooting_nodes: 60
    dt_ocp: 0.01
    nb_iterations_max: 1
    reference_is_placement: true   # otherwise, translation
    keep_original_ee_rotation: false
    armature: [0.1,0.1,0.1,0.1,0.1,0.1,0.1]
    # armature: [0.0,0.0,0.0,0.0,0.0,0.0,0.0]
    
    # w_frame_running:  50  # T265
    # w_frame_terminal: 50  # T265
    w_frame_running:  5  # VS
    w_frame_terminal: 5  # VS
    w_x_reg_running:  0.001
    w_x_reg_terminal: 0.001
    w_u_reg_running: 0.003
    diag_q_reg_running: [0.1,
                         0.1,
                         0.1,
                         0.1,
                         0.1,
                         0.1,
                         0.1]
    diag_v_reg_running: [10.0,
                         10.0,
                         10.0,
                         10.0,
                         100.0,
                         100.0,
                         100.0
                         ]
    diag_u_reg_running: [1.0,1.0,1.0,1.0,1.0,1.0,1.0]
    
    # pose format: px, py, pz,    qx, qy, qz, qw
    pose_e_c: [0.137, -0.01, -0.059,  0.0869, -0.0866, -0.70365, 0.69986]  # Camera CALIBRATION d455

    # Target relative pose
    # pose_c_o_ref: [0.0, 0.0, 0.71,     1, 0, 0, 0 ]   # Apriltag 0
    # pose_c_o_ref: [-0.03017028, 0.0899488, 0.60250643,  0.44333751,  0.44584125, -0.53308101,  0.56626288] # Cheezit
    # pose_c_o_ref: [0.0, 0.1, 0.5,    -0.5, -0.5, 0.5, -0.5 ]   # Cheezit
    pose_c_o_ref: [-0.0399200282198421, 0.06638413117011709, 0.4704659749834999, 0.1644332627969024, 0.6832111200594132, -0.5174592818349182, 0.48834781556460893]     # Cheezit side
    # pose_c_o_ref: [0.0, 0.060, 0.55,   -0.1474599121420375, -0.6722591020570695, 0.7138663759843439, -0.1292983806993129 ]   # Mustard lookup up
    # pose_c_o_ref: [0.054, 0.0654, 0.5,   -0.1474599121420375, 0.40176469195778003, -0.21992470044436893, 0.6435384341970608 ]   # rotated 4 oclock
