model_pinocchio_vs_franka_controller:
  type: panda_torque_mpc/ModelPinocchioVsFrankaController
  arm_id: $(arg arm_id)
  urdf_path: /home/mfourmy/Desktop/panda_inertias.urdf


joint_space_ID_controller:
    type: panda_torque_mpc/JointSpaceIDController
    arm_id: $(arg arm_id)
    urdf_path: /home/mfourmy/Desktop/panda_inertias.urdf
    joint_names:
        - $(arg arm_id)_joint1
        - $(arg arm_id)_joint2
        - $(arg arm_id)_joint3
        - $(arg arm_id)_joint4
        - $(arg arm_id)_joint5
        - $(arg arm_id)_joint6
        - $(arg arm_id)_joint7

    # Gains for IDControl
    # Kp: 500  # Stiff
    # Kd: 50  # Stiff
    Kp: 50
    Kd: 5
    # Gains for IDControlSimplified
    kp_gains:
        - 60.0
        - 60.0
        - 60.0
        - 60.0
        - 20.0
        - 10.0
        - 5.0
    kd_gains:
        - 5.0
        - 5.0
        - 5.0
        - 2.0
        - 2.0
        - 2.0
        - 1.0
    # Trajectory simulation
    delta_q:
        - -0.5
        - 0.5
        - 0.5
        - 0.5
        - 0.5
        - 0.5
        - 0.5
    period_q:
        - 3.0
        - 3.0
        - 3.0
        - 3.0
        - 3.0
        - 3.0
        - 3.0
    publish_rate: 10.0
    use_pinocchio: true
    alpha_dq_filter: 0.99 # should be close to 1 and <= 1.0
    # 0: IDControl
    # 1: IDControlSimplified
    # 2: PDGravity
    control_variant: 0